// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTOGENERATED by `npm run generate:local-host-bytecode` via `cast interface`.
// DO NOT EDIT — your changes will be overwritten. See internal/generateLocalHostBytecode.ts.

import {FheType} from "../../shared/FheType.sol";

library FHEVMExecutor {
    type Operators is uint8;
}

interface ICleartextArithmetic {
    error AddressEmptyCode(address target);
    error CleartextErrorHandleChainIdMismatch(bytes32 handle, uint64 handleChainId, uint64 blockChainId);
    error CleartextErrorNotABoolean(uint256 value);
    error CleartextErrorPlaintextTooWide(uint256 value, FheType fheType);
    error CleartextErrorUnsupportedBinaryOp(FHEVMExecutor.Operators op);
    error CleartextErrorUnsupportedNaryOp(FHEVMExecutor.Operators op);
    error CleartextErrorUnsupportedTernaryOp(FHEVMExecutor.Operators op);
    error CleartextErrorUnsupportedType();
    error CleartextErrorUnsupportedUnaryOp(FHEVMExecutor.Operators op);
    error ERC1967InvalidImplementation(address implementation);
    error ERC1967NonPayable();
    error FailedCall();
    error InvalidInitialization();
    error NotHostOwner(address sender);
    error NotInitializing();
    error NotInitializingFromEmptyProxy();
    error UUPSUnauthorizedCallContext();
    error UUPSUnsupportedProxiableUUID(bytes32 slot);

    event Initialized(uint64 version);
    event Upgraded(address indexed implementation);

    function IS_CLEARTEXT() external view returns (bool);
    function UPGRADE_INTERFACE_VERSION() external view returns (string memory);
    function getCleartextDBAddress() external view returns (address);
    function getVersion() external pure returns (string memory);
    function initializeFromEmptyProxy() external;
    function plaintexts(bytes32 handle) external view returns (uint256);
    function proxiableUUID() external view returns (bytes32);
    function recordBinaryOp(
        FHEVMExecutor.Operators op,
        bytes32 result,
        bytes32 lhs,
        bytes32 rhs,
        bytes1 scalarByte,
        FheType fheType
    ) external;
    function recordCast(bytes32 result, bytes32 ct, FheType toType) external;
    function recordNaryOp(
        FHEVMExecutor.Operators op,
        bytes32 result,
        bytes32 value,
        bytes32[] memory values,
        FheType fheType
    ) external;
    function recordRand(bytes32 result, FheType randType, bytes16 seed) external;
    function recordRandBounded(bytes32 result, uint256 upperBound, bytes16 seed) external;
    function recordTernaryOp(FHEVMExecutor.Operators op, bytes32 result, bytes32 lhs, bytes32 middle, bytes32 rhs)
        external;
    function recordTrivialEncrypt(bytes32 result, uint256 pt, FheType toType) external;
    function recordUnaryOp(FHEVMExecutor.Operators op, bytes32 result, bytes32 ct, FheType fheType) external;
    function recordVerifyInput(bytes32 result, bytes32 inputHandle, bytes memory inputProof, FheType inputType) external;
    function reinitializeV2() external;
    function upgradeToAndCall(address newImplementation, bytes memory data) external payable;
}
