// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTOGENERATED by `npm run generate:local-host-bytecode` via `cast interface`.
// DO NOT EDIT — your changes will be overwritten. See internal/generateLocalHostBytecode.ts.

interface IKMSVerifier {
    error AddressEmptyCode(address target);
    error DeserializingDecryptionProofFail();
    error DeserializingExtraDataFail();
    error ECDSAInvalidSignature();
    error ECDSAInvalidSignatureLength(uint256 length);
    error ECDSAInvalidSignatureS(bytes32 s);
    error ERC1967InvalidImplementation(address implementation);
    error ERC1967NonPayable();
    error EmptyDecryptionProof();
    error FailedCall();
    error InvalidInitialization();
    error KMSInvalidSigner(address invalidSigner);
    error KMSSignatureThresholdNotReached(uint256 numSignatures);
    error KMSZeroSignature();
    error NotHostOwner(address sender);
    error NotInitializing();
    error NotInitializingFromEmptyProxy();
    error UUPSUnauthorizedCallContext();
    error UUPSUnsupportedProxiableUUID(bytes32 slot);
    error UnsupportedExtraDataVersion(uint8 version);

    event EIP712DomainChanged();
    event Initialized(uint64 version);
    event Upgraded(address indexed implementation);

    function DECRYPTION_RESULT_TYPEHASH() external view returns (bytes32);
    function EIP712_PUBLIC_DECRYPT_TYPE() external view returns (string memory);
    function UPGRADE_INTERFACE_VERSION() external view returns (string memory);
    function eip712Domain()
        external
        view
        returns (
            bytes1 fields,
            string memory name,
            string memory version,
            uint256 chainId,
            address verifyingContract,
            bytes32 salt,
            uint256[] memory extensions
        );
    function getContextSignersAndThresholdFromExtraData(bytes memory extraData)
        external
        view
        returns (address[] memory signers, uint256 threshold);
    function getCurrentKmsContextId() external view returns (uint256);
    function getKmsSigners() external view returns (address[] memory);
    function getSignersForKmsContext(uint256 kmsContextId) external view returns (address[] memory);
    function getThreshold() external view returns (uint256);
    function getVersion() external pure returns (string memory);
    function initializeFromEmptyProxy(address verifyingContractSource, uint64 chainIDSource) external;
    function isSigner(address account) external view returns (bool);
    function proxiableUUID() external view returns (bytes32);
    function reinitializeV3() external;
    function upgradeToAndCall(address newImplementation, bytes memory data) external payable;
    function verifyDecryptionEIP712KMSSignatures(
        bytes32[] memory handlesList,
        bytes memory decryptedResult,
        bytes memory decryptionProof
    ) external returns (bool);
}
