// SPDX-License-Identifier: BSD-3-Clause-Clear

pragma solidity ^0.8.24;

// Auto-generated by create2-deploy/script/FhevmComputeCreate2Addresses.s.sol - do not edit by hand.
// CREATE2 addresses. Valid ONLY for this (deployer, version, deploymentId) triple:
//   deployer     0x37AC010c1c566696326813b840319B58Bb5840E4
//   deploymentId cleartext-v13-sepolia-2026-10-05-1
//   version      0.13

address constant ACL_ADDRESS = address(0xda065e59B89aE073319a04c68ad4C3440665C1E2);

address constant FHEVM_EXECUTOR_ADDRESS = address(0xEe5a510A6DF73827B3cb8A49D2d424c79fC4e590);

address constant KMS_VERIFIER_ADDRESS = address(0xd7dD9AfDF57442C1345a67c699f69B10B4dDc330);

address constant INPUT_VERIFIER_ADDRESS = address(0xC8321bBACA33A3083231eb998e3a28Da6a661C6e);

address constant HCU_LIMIT_ADDRESS = address(0x155593EA16Ca46BFCca731067627187F132798EC);

address constant PROTOCOL_CONFIG_ADDRESS = address(0x7C9d5217026f700BDc29271765927B60CF3aF5ac);

address constant KMS_GENERATION_ADDRESS = address(0x612D731671990e5c297e1526B50593856B0300e6);

address constant CLEARTEXT_ARITHMETIC_ADDRESS = address(0x79b4520805DE66f034E359Ff898B452a423194A6);

address constant CLEARTEXT_DB_ADDRESS = address(0x075b091820C057bB0fC52B9f9C3aa6E2528e88e9);

address constant PAUSER_SET_ADDRESS = address(0x448c8648CE056B0b56637344fcaeFe2476c88Cef);
