// The stack's shape — which proxies exist and in what order they are materialized — is written down
// SIX times, in four notations, by hand:
//
//   1. pkg/ts/deploy.ts                              TypeScript deploy
//   2. pkg/forge/src/FhevmCleartextDeploy.sol                 forge library (the consumer-facing one)
//   3. pkg/forge/script/FhevmDeployScript.s.sol      forge script, compiles pkg/src
//   4. pkg/forge/script/DeployLocalStack.s.sol       forge script, uses the generated bytecode
//   5. create2-deploy/script/FhevmCreate2Base.s.sol  the CREATE2 role table
//   6. scripts/anvil-lib.sh                          bash deploy, via cast
//
// Nothing checked that the six agreed. They cannot be checked by a compiler — different languages,
// different notations, each internally consistent — so drift between them is silent, and the failure
// mode is a stack that deploys cleanly with the wrong implementation behind a proxy.
//
// That is not hypothetical. Deriving v12 from v13 broke this four separate ways: array sizes, a
// hardcoded ACLOwner nonce, twelve hardcoded loop bounds, and a test that contradicted the directory it
// read. Each was correct in v13 by coincidence and wrong the moment the stack changed shape.
//
// ## Why a text scan, and not a nicer design
//
// This reads the six files as TEXT and compares the orders it finds. That is unusual, and it is a
// deliberate stepping stone rather than the destination: the destination is ONE generated table that all
// six consume, at which point this test becomes unnecessary and should be deleted. But a refactor that
// merges six copies has to start by proving they are equivalent — otherwise it silently adopts whichever
// copy the author happened to read. This is that proof, and it keeps them equivalent in the meantime.
//
// A scan has one real weakness worth stating: it verifies ORDER, not behaviour. Two layers can agree on
// the sequence and still pass different initializer arguments. Those arguments are deliberately NOT
// unified — they are the documented override point (see FhevmCleartextDeploy's `_fhevmProtocolConfig`) — so they
// stay covered by the deploy tests and `VerifyFhevmDeploy`, which read them back off a live chain.

import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';
import { PACKAGE_ROOT_ABS_PATH } from '../internal/constants.ts';

////////////////////////////////////////////////////////////////////////////////

/**
 * The canonical name of each position: the ROLE (the proxy), not the implementation behind it.
 *
 * The distinction matters because three positions are cleartext substitutions — `CleartextFHEVMExecutor`
 * is the implementation deployed behind the `FHEVM_EXECUTOR` proxy — and a comparison keyed on the
 * implementation name would report those three as mismatches in every layer that names the proxy.
 */
function canonicalRole(name: string): string {
  const snake = name
    .replace(/_?(ADDRESS|CREATION_CODE)$/, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toUpperCase();
  // The Forge variants are the same ROLE deployed with different bytecode — FhevmCleartextDeploy uses them so
  // its in-process stack can call cheatcodes, DeployLocalStack cannot because it broadcasts. This test
  // compares ORDER, and the order is identical, so the infix is dropped before anything else. Were it
  // not, every layer would appear to disagree with FhevmCleartextDeploy about three positions that never moved.
  const deforged = snake.replace(/^CLEARTEXT_FORGE_/, 'CLEARTEXT_');
  // The cleartext variants sit behind the stock proxies; CleartextArithmetic and CleartextDB are their
  // own roles, so only the four substitutions are rewritten. `CleartextACL` exists but no deploy layer
  // names it, so ACL reaches this scan only through its Forge variant, which the line above has just
  // reduced to CLEARTEXT_ACL.
  return deforged.replace(/^CLEARTEXT_(ACL|FHEVM_EXECUTOR|KMS_VERIFIER|INPUT_VERIFIER)$/, '$1');
}

/** Every layer that chooses an ACL implementation, for the guard below. */
const DEPLOY_LAYER_FILES: ReadonlyArray<{ readonly label: string; readonly path: string; readonly optional?: true }> = [
  { label: 'pkg/ts/deploy.ts', path: 'pkg/ts/deploy.ts' },
  { label: 'pkg/forge/src/FhevmCleartextDeploy.sol', path: 'pkg/forge/src/FhevmCleartextDeploy.sol' },
  { label: 'pkg/forge/script/FhevmDeployScript.s.sol', path: 'pkg/forge/script/FhevmDeployScript.s.sol' },
  { label: 'pkg/forge/script/DeployLocalStack.s.sol', path: 'pkg/forge/script/DeployLocalStack.s.sol' },
  { label: 'create2-deploy/script/FhevmCreate2Base.s.sol', path: 'create2-deploy/script/FhevmCreate2Base.s.sol' },
  { label: 'scripts/anvil-lib.sh', path: 'scripts/anvil-lib.sh' },
  // The upgrade path deploys fresh implementations too. Left out at first, and it was the one layer
  // still reaching for the plain ACL — an upgraded stack would have lost the marker it deployed with.
  { label: 'pkg/ts/upgrade.ts', path: 'pkg/ts/upgrade.ts' },
  {
    label: 'create2-deploy/script/upgrade/FhevmUpgradeBase.s.sol',
    path: 'create2-deploy/script/upgrade/FhevmUpgradeBase.s.sol',
    // The CREATE2 upgrade lane is what a rotation deletes from V(N-1) (ROTATION.md § 1), so on the next
    // generation's branch this file is legitimately gone. Everything else in the list stays for the life
    // of the generation, so only this entry may be absent.
    optional: true,
  },
];

function read(relativePath: string): string {
  return readFileSync(join(PACKAGE_ROOT_ABS_PATH, relativePath), 'utf8');
}

/** The text between two markers, so a scan cannot wander into an unrelated list in the same file. */
function section(source: string, start: string, end: string, label: string): string {
  const from = source.indexOf(start);
  assert.notEqual(from, -1, `${label}: could not find the start marker ${JSON.stringify(start)}`);
  const to = source.indexOf(end, from + start.length);
  assert.notEqual(to, -1, `${label}: could not find the end marker after the start`);
  return source.slice(from, to);
}

function matchAll(source: string, pattern: RegExp, label: string): string[] {
  const found = [...source.matchAll(pattern)].map((m) => {
    const captured = m[1];
    assert.ok(captured !== undefined, `${label}: pattern matched with no capture group`);
    return canonicalRole(captured);
  });
  assert.ok(found.length > 0, `${label}: found no entries — the file's shape changed, so this scan is blind`);
  return found;
}

////////////////////////////////////////////////////////////////////////////////

/** Source of truth for the comparison: the TypeScript deploy, which the whole package is built around. */
function tsDeployOrder(): string[] {
  const targets = section(
    read('pkg/ts/deploy.ts'),
    'const targets: readonly UpgradeTarget[] = [',
    '\n  ];',
    'pkg/ts/deploy.ts',
  );
  return matchAll(targets, /contractName: '([A-Za-z0-9]+)'/g, 'pkg/ts/deploy.ts');
}

const LAYERS: ReadonlyArray<{ readonly label: string; readonly order: () => string[] }> = [
  {
    label: 'pkg/forge/src/FhevmCleartextDeploy.sol',
    order: () =>
      matchAll(
        section(
          read('pkg/forge/src/FhevmCleartextDeploy.sol'),
          'implementations[0] =',
          '\n    }',
          'FhevmCleartextDeploy.sol',
        ),
        /_create\(([A-Z0-9_]+)_CREATION_CODE/g,
        'pkg/forge/src/FhevmCleartextDeploy.sol',
      ),
  },
  {
    label: 'pkg/forge/script/FhevmDeployScript.s.sol',
    order: () =>
      matchAll(
        section(
          read('pkg/forge/script/FhevmDeployScript.s.sol'),
          'ACLOwner.Op[] memory ops = new ACLOwner.Op[](PROXY_COUNT);',
          'aclOwner.upgrade(ops);',
          'FhevmDeployScript.s.sol',
        ),
        /address\(new ([A-Za-z0-9]+)\(\)\)/g,
        'pkg/forge/script/FhevmDeployScript.s.sol',
      ),
  },
  {
    label: 'pkg/forge/script/DeployLocalStack.s.sol',
    order: () =>
      matchAll(
        section(
          read('pkg/forge/script/DeployLocalStack.s.sol'),
          'ACLOwner.Op[] memory ops = new ACLOwner.Op[](PROXY_COUNT);',
          'upgrade(ops)',
          'DeployLocalStack.s.sol',
        ),
        /_create\(([A-Z0-9_]+)_CREATION_CODE/g,
        'pkg/forge/script/DeployLocalStack.s.sol',
      ),
  },
  {
    label: 'create2-deploy/script/FhevmCreate2Base.s.sol',
    order: () =>
      matchAll(
        section(
          read('create2-deploy/script/FhevmCreate2Base.s.sol'),
          'function _implArtifact(',
          'implementation index out of range',
          'FhevmCreate2Base.s.sol',
        ),
        /:([A-Za-z0-9]+)";/g,
        'create2-deploy/script/FhevmCreate2Base.s.sol',
      ),
  },
  {
    label: 'scripts/anvil-lib.sh',
    order: () =>
      matchAll(
        section(read('scripts/anvil-lib.sh'), 'ops="[($ACL_ADDRESS', ']"', 'anvil-lib.sh'),
        /\(\$([A-Z0-9_]+)_ADDRESS,/g,
        'scripts/anvil-lib.sh',
      ),
  },
];

////////////////////////////////////////////////////////////////////////////////

void test('every deploy layer materializes the same proxies in the same order', () => {
  const expected = tsDeployOrder();

  for (const layer of LAYERS) {
    assert.deepEqual(
      layer.order(),
      expected,
      `${layer.label} materializes a different order than pkg/ts/deploy.ts.\n` +
        `  If a proxy was added or removed, EVERY layer listed at the top of this file has to change.\n` +
        `  If only the order differs, one of them is deploying the wrong implementation behind a proxy.`,
    );
  }
});

////////////////////////////////////////////////////////////////////////////////

void test('the create2 role table agrees with the deploy order', () => {
  // _allProxyRoles() is ACL followed by _sharedProxyRoles(), and its POSITIONS are what
  // MaterializeInitData.initData(i) and _implArtifact(i) are indexed by — so it has to match too.
  const base = read('create2-deploy/script/FhevmCreate2Base.s.sol');
  const shared = matchAll(
    section(base, 'function _sharedProxyRoles()', '\n    }', 'FhevmCreate2Base _sharedProxyRoles'),
    /R_([A-Z0-9_]+);/g,
    'FhevmCreate2Base _sharedProxyRoles',
  );
  assert.deepEqual(['ACL', ...shared], tsDeployOrder(), 'the create2 role table must match the deploy order');
});

/**
 * `ACL.sol` is the upstream contract and this package must never deploy it. A cleartext stack has to
 * advertise itself, and the ACL is the one address every consumer already holds through `ZamaConfig`, so
 * an unmarked ACL there is indistinguishable from a production deployment. Only `CleartextACL` (every
 * broadcast path) or `CleartextForgeACL` (the in-process forge stack) may sit behind the ACL proxy.
 *
 * A text scan for the same reason the order comparison above is one: these layers are four languages and
 * no compiler sees them together.
 */
void test('no deploy layer deploys the plain ACL', () => {
  // Each pattern is a way a layer could name the plain contract. The lookbehind keeps
  // CLEARTEXT_ACL_CREATION_CODE and EMPTY_UUPS_PROXY_ACL_CREATION_CODE out of it.
  const forbidden: ReadonlyArray<{ readonly pattern: RegExp; readonly what: string }> = [
    { pattern: /(?<![A-Za-z_])ACL_CREATION_CODE/, what: 'the plain ACL bytecode blob' },
    { pattern: /new ACL\(\)/, what: 'a direct `new ACL()`' },
    { pattern: /contracts\/ACL\.sol:ACL\b/, what: 'the ACL.sol forge artifact' },
    { pattern: /artifacts\/ACL\.(?:js|ts)\b/, what: 'the ACL TypeScript artifact' },
  ];

  const offences: string[] = [];
  for (const { label, path, optional } of DEPLOY_LAYER_FILES) {
    if (optional === true && !existsSync(join(PACKAGE_ROOT_ABS_PATH, path))) continue;
    const source = read(path);
    for (const { pattern, what } of forbidden) {
      if (pattern.test(source)) offences.push(`${label} reaches for ${what}`);
    }
  }

  assert.deepEqual(offences, [], 'a deploy layer still names the plain ACL');
});
