// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.24;

// GENERATED by scripts/gen-op-dapp.py and - do not edit by hand.

import {FHE} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";
import {FHEext} from "../utils/FHEext.sol";

// FHE.and for the operator vector tests: one wrapper per overload FHE.sol
// declares, each calling exactly that overload. Inputs and result grants go
// through FHEext.
contract AndDapp is ZamaEthereumConfig {
    function and_e8_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint8(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function and_e8_e16(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint8(a, proof), FHEext.fromExternalEuint16(b, proof)));
    }

    function and_e8_e32(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint8(a, proof), FHEext.fromExternalEuint32(b, proof)));
    }

    function and_e8_e64(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint8(a, proof), FHEext.fromExternalEuint64(b, proof)));
    }

    function and_e8_e128(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint8(a, proof), FHEext.fromExternalEuint128(b, proof)));
    }

    function and_e8_e256(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint8(a, proof), FHEext.fromExternalEuint256(b, proof)));
    }

    function and_e16_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint16(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function and_e16_e16(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint16(a, proof), FHEext.fromExternalEuint16(b, proof)));
    }

    function and_e16_e32(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint16(a, proof), FHEext.fromExternalEuint32(b, proof)));
    }

    function and_e16_e64(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint16(a, proof), FHEext.fromExternalEuint64(b, proof)));
    }

    function and_e16_e128(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint16(a, proof), FHEext.fromExternalEuint128(b, proof)));
    }

    function and_e16_e256(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint16(a, proof), FHEext.fromExternalEuint256(b, proof)));
    }

    function and_e32_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint32(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function and_e32_e16(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint32(a, proof), FHEext.fromExternalEuint16(b, proof)));
    }

    function and_e32_e32(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint32(a, proof), FHEext.fromExternalEuint32(b, proof)));
    }

    function and_e32_e64(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint32(a, proof), FHEext.fromExternalEuint64(b, proof)));
    }

    function and_e32_e128(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint32(a, proof), FHEext.fromExternalEuint128(b, proof)));
    }

    function and_e32_e256(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint32(a, proof), FHEext.fromExternalEuint256(b, proof)));
    }

    function and_e64_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint64(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function and_e64_e16(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint64(a, proof), FHEext.fromExternalEuint16(b, proof)));
    }

    function and_e64_e32(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint64(a, proof), FHEext.fromExternalEuint32(b, proof)));
    }

    function and_e64_e64(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint64(a, proof), FHEext.fromExternalEuint64(b, proof)));
    }

    function and_e64_e128(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint64(a, proof), FHEext.fromExternalEuint128(b, proof)));
    }

    function and_e64_e256(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint64(a, proof), FHEext.fromExternalEuint256(b, proof)));
    }

    function and_e128_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint128(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function and_e128_e16(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint128(a, proof), FHEext.fromExternalEuint16(b, proof)));
    }

    function and_e128_e32(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint128(a, proof), FHEext.fromExternalEuint32(b, proof)));
    }

    function and_e128_e64(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint128(a, proof), FHEext.fromExternalEuint64(b, proof)));
    }

    function and_e128_e128(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint128(a, proof), FHEext.fromExternalEuint128(b, proof)));
    }

    function and_e128_e256(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint128(a, proof), FHEext.fromExternalEuint256(b, proof)));
    }

    function and_e256_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint256(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function and_e256_e16(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint256(a, proof), FHEext.fromExternalEuint16(b, proof)));
    }

    function and_e256_e32(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint256(a, proof), FHEext.fromExternalEuint32(b, proof)));
    }

    function and_e256_e64(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint256(a, proof), FHEext.fromExternalEuint64(b, proof)));
    }

    function and_e256_e128(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint256(a, proof), FHEext.fromExternalEuint128(b, proof)));
    }

    function and_e256_e256(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint256(a, proof), FHEext.fromExternalEuint256(b, proof)));
    }

    function and_e1_e1(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEbool(a, proof), FHEext.fromExternalEbool(b, proof)));
    }

    function and_e8_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint8(a, proof), b));
    }

    function and_e16_u16(bytes32 a, uint16 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint16(a, proof), b));
    }

    function and_e32_u32(bytes32 a, uint32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint32(a, proof), b));
    }

    function and_e64_u64(bytes32 a, uint64 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint64(a, proof), b));
    }

    function and_e128_u128(bytes32 a, uint128 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint128(a, proof), b));
    }

    function and_e256_u256(bytes32 a, uint256 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEuint256(a, proof), b));
    }

    function and_e1_u1(bytes32 a, bool b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(FHEext.fromExternalEbool(a, proof), b));
    }

    function and_u8_e8(uint8 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(a, FHEext.fromExternalEuint8(b, proof)));
    }

    function and_u16_e16(uint16 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(a, FHEext.fromExternalEuint16(b, proof)));
    }

    function and_u32_e32(uint32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(a, FHEext.fromExternalEuint32(b, proof)));
    }

    function and_u64_e64(uint64 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(a, FHEext.fromExternalEuint64(b, proof)));
    }

    function and_u128_e128(uint128 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(a, FHEext.fromExternalEuint128(b, proof)));
    }

    function and_u256_e256(uint256 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(a, FHEext.fromExternalEuint256(b, proof)));
    }

    function and_u1_e1(bool a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.and(a, FHEext.fromExternalEbool(b, proof)));
    }
}
