// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.24;

// GENERATED by scripts/gen-op-dapp.py neg - do not edit by hand.

import {FHE} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";
import {FHEext} from "../utils/FHEext.sol";

// FHE.neg for the operator vector tests: one wrapper per overload FHE.sol
// declares, each calling exactly that overload. Inputs and result grants go
// through FHEext.
contract NegDapp is ZamaEthereumConfig {
    function neg_e8(bytes32 a, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.neg(FHEext.fromExternalEuint8(a, proof)));
    }

    function neg_e16(bytes32 a, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.neg(FHEext.fromExternalEuint16(a, proof)));
    }

    function neg_e32(bytes32 a, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.neg(FHEext.fromExternalEuint32(a, proof)));
    }

    function neg_e64(bytes32 a, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.neg(FHEext.fromExternalEuint64(a, proof)));
    }

    function neg_e128(bytes32 a, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.neg(FHEext.fromExternalEuint128(a, proof)));
    }

    function neg_e256(bytes32 a, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.neg(FHEext.fromExternalEuint256(a, proof)));
    }
}
