// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.24;

// GENERATED by scripts/gen-op-dapp.py rem - do not edit by hand.

import {FHE} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";
import {FHEext} from "../utils/FHEext.sol";

// FHE.rem for the operator vector tests: one wrapper per overload FHE.sol
// declares, each calling exactly that overload. Inputs and result grants go
// through FHEext.
contract RemDapp is ZamaEthereumConfig {
    function rem_e8_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rem(FHEext.fromExternalEuint8(a, proof), b));
    }

    function rem_e16_u16(bytes32 a, uint16 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rem(FHEext.fromExternalEuint16(a, proof), b));
    }

    function rem_e32_u32(bytes32 a, uint32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rem(FHEext.fromExternalEuint32(a, proof), b));
    }

    function rem_e64_u64(bytes32 a, uint64 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rem(FHEext.fromExternalEuint64(a, proof), b));
    }

    function rem_e128_u128(bytes32 a, uint128 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rem(FHEext.fromExternalEuint128(a, proof), b));
    }
}
