// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.24;

// GENERATED by scripts/gen-op-dapp.py rotr - do not edit by hand.

import {FHE} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";
import {FHEext} from "../utils/FHEext.sol";

// FHE.rotr for the operator vector tests: one wrapper per overload FHE.sol
// declares, each calling exactly that overload. Inputs and result grants go
// through FHEext.
contract RotrDapp is ZamaEthereumConfig {
    function rotr_e8_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint8(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function rotr_e16_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint16(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function rotr_e32_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint32(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function rotr_e64_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint64(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function rotr_e128_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint128(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function rotr_e256_e8(bytes32 a, bytes32 b, bytes calldata proof) external returns (bytes32) {
        return
            FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint256(a, proof), FHEext.fromExternalEuint8(b, proof)));
    }

    function rotr_e8_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint8(a, proof), b));
    }

    function rotr_e16_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint16(a, proof), b));
    }

    function rotr_e32_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint32(a, proof), b));
    }

    function rotr_e64_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint64(a, proof), b));
    }

    function rotr_e128_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint128(a, proof), b));
    }

    function rotr_e256_u8(bytes32 a, uint8 b, bytes calldata proof) external returns (bytes32) {
        return FHEext.allowToBytes32(FHE.rotr(FHEext.fromExternalEuint256(a, proof), b));
    }
}
