// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// GENERATED by internal/generateVersion.ts - do not edit by hand.
// The source of truth is pkg/package.json#version.
library StdFhevmVersion {
    string internal constant VERSION = "0.14.0-0";
}
