// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

import {console} from "forge-std/Script.sol";
import {FhevmUpgradeBase} from "./FhevmUpgradeBase.s.sol";

/**
 *  Two-pass CREATE2 computation for upgrading a supplied live v13 stack.
 *
 *  v14 creates no proxy, so pass 1 has nothing to predict: it writes the addresses file the
 *  implementations are compiled against (all nine live proxies) and records its hash. Pass 2, after the
 *  rebuild, asserts that file did not move, predicts the seven implementations and seals the manifest.
 */
contract FhevmComputeUpgradeAddresses is FhevmUpgradeBase {
    function run() external {
        _loadUpgradeConfig();
        vm.createDir(cfg.outDir, true);
        uint256 pass = vm.envUint("FHEVM_PASS");
        if (pass == 1) _pass1();
        else if (pass == 2) _pass2();
        else revert("FhevmComputeUpgradeAddresses: FHEVM_PASS must be 1 or 2");
    }

    function _pass1() private {
        _banner("upgrade pass 1/2 - live addresses");
        _writeAddresses();

        string memory o = "upgradePass1";
        string memory out = vm.serializeBytes32(o, "addressesHash", _addressesHash());
        vm.writeJson(out, _scratchPath());

        console.log("  PROTOCOL_CONFIG_ADDRESS", existingProtocolConfig);
        console.log("  KMS_GENERATION_ADDRESS ", existingKmsGeneration);
        console.log("  wrote", _addressesPath());
    }

    function _pass2() private {
        _banner("upgrade pass 2/2 - implementations, assert, seal");
        string memory scratch = vm.readFile(_scratchPath());
        require(
            _addressesHash() == vm.parseJsonBytes32(scratch, ".addressesHash"),
            "upgrade pass2: addresses file moved since pass 1"
        );

        string[] memory roles = _upgradeProxyRoles();
        address[] memory implementations = new address[](roles.length);
        for (uint256 i; i < roles.length; i++) {
            bytes memory code = _initCode(_upgradeImplArtifact(i));
            require(code.length != 0, string.concat("upgrade pass2: missing artifact for ", roles[i]));
            require(code.length <= MAX_INITCODE_SIZE, string.concat("upgrade pass2: EIP-3860 overflow in ", roles[i]));
            implementations[i] = _predictCreate2Address(_implRole(roles[i]), code);
            console.log(string.concat("  IMPL_", roles[i]), implementations[i]);
        }

        _writeManifest(implementations);
        console.log("  wrote", _manifestPath());
    }

    /// @dev The addresses file as pass 1 wrote it, so pass 2 can tell a rebuild from a re-targeting.
    function _addressesHash() private view returns (bytes32) {
        return keccak256(bytes(vm.readFile(_addressesPath())));
    }

    function _writeAddresses() private {
        string memory source = string.concat(
            "// SPDX-License-Identifier: BSD-3-Clause-Clear\npragma solidity ^0.8.24;\n",
            "// Generated by FhevmComputeUpgradeAddresses; do not edit.\n"
        );
        source = string.concat(source, _constant(R_ACL, existingAcl));
        source = string.concat(source, _constant(R_FHEVM_EXECUTOR, existingExecutor));
        source = string.concat(source, _constant(R_KMS_VERIFIER, existingKmsVerifier));
        source = string.concat(source, _constant(R_INPUT_VERIFIER, existingInputVerifier));
        source = string.concat(source, _constant(R_HCU_LIMIT, existingHcuLimit));
        source = string.concat(source, _constant(R_PROTOCOL_CONFIG, existingProtocolConfig));
        source = string.concat(source, _constant(R_KMS_GENERATION, existingKmsGeneration));
        source = string.concat(source, _constant(R_CLEARTEXT_ARITHMETIC, existingArithmetic));
        source = string.concat(source, _constant(R_CLEARTEXT_DB, existingDb));
        source = string.concat(source, _constant(R_PAUSER_SET, existingPauserSet));
        vm.writeFile(_addressesPath(), source);
    }

    function _constant(string memory name, address value) private pure returns (string memory) {
        return string.concat("address constant ", name, " = address(", vm.toString(value), ");\n");
    }

    function _writeManifest(address[] memory implementations) private {
        string memory addressMap = _serializeAddresses(implementations);
        string memory o = "upgradeManifest";
        vm.serializeUint(o, "chainId", cfg.chainId);
        vm.serializeString(o, "version", cfg.version);
        vm.serializeString(o, "deploymentId", cfg.deploymentId);
        vm.serializeAddress(o, "deployer", cfg.deployer);
        vm.serializeAddress(o, "admin", cfg.admin);
        vm.serializeAddress(o, "factory", CREATE2_FACTORY);
        vm.serializeUint(o, "confirmations", cfg.confirmations);
        string memory out = vm.serializeString(o, "address", addressMap);
        vm.writeJson(out, _manifestPath());
    }

    function _serializeAddresses(address[] memory implementations) private returns (string memory out) {
        string memory o = "upgradeAddressMap";
        vm.serializeAddress(o, R_ACL, existingAcl);
        vm.serializeAddress(o, R_FHEVM_EXECUTOR, existingExecutor);
        vm.serializeAddress(o, R_KMS_VERIFIER, existingKmsVerifier);
        vm.serializeAddress(o, R_INPUT_VERIFIER, existingInputVerifier);
        vm.serializeAddress(o, R_HCU_LIMIT, existingHcuLimit);
        vm.serializeAddress(o, R_PROTOCOL_CONFIG, existingProtocolConfig);
        vm.serializeAddress(o, R_KMS_GENERATION, existingKmsGeneration);
        vm.serializeAddress(o, R_CLEARTEXT_ARITHMETIC, existingArithmetic);
        vm.serializeAddress(o, R_CLEARTEXT_DB, existingDb);
        vm.serializeAddress(o, R_PAUSER_SET, existingPauserSet);
        vm.serializeAddress(o, R_ACL_OWNER, existingAclOwner);

        string[] memory roles = _upgradeProxyRoles();
        require(implementations.length == roles.length, "FhevmComputeUpgradeAddresses: implementation arity");
        for (uint256 i; i + 1 < roles.length; i++) {
            vm.serializeAddress(o, _implRole(roles[i]), implementations[i]);
        }
        out = vm.serializeAddress(o, _implRole(roles[roles.length - 1]), implementations[roles.length - 1]);
    }
}
