// AUTO-GENERATED by `fhevm-npm generate cleartext-config` from sdk/cleartext-config.json — DO NOT EDIT.
// The v14 TypeScript face.

// uint48(uint256(keccak256("fhevm.cheat.chainId cleartext gateway")))
export const CLEARTEXT_GATEWAY_CHAIN_ID = 100733346448153n;

export const CLEARTEXT_RELAYER_URL = 'https://relayer.cleartext.foo';

// address(uint160(uint256(keccak256("fhevm.cheat.address cleartext input verification"))))
export const CLEARTEXT_INPUT_VERIFICATION_ADDRESS = '0x6189F6c0c3E40B4a3c72ec86262295D78d845297';

// address(uint160(uint256(keccak256("fhevm.cheat.address cleartext decryption"))))
export const CLEARTEXT_DECRYPTION_ADDRESS = '0xEaaA2FC6BC259dF015Aa7Dc8e59e0B67df622721';

export const CLEARTEXT_COPROCESSOR_COUNT = 4;

export const CLEARTEXT_COPROCESSOR_THRESHOLD = 4;

export const CLEARTEXT_KMS_NODE_COUNT = 4;

// type(uint48).max
export const CLEARTEXT_HCU_CAP_PER_BLOCK = 281474976710655n;

export const CLEARTEXT_MAX_HCU_DEPTH_PER_TX = 5000000n;

export const CLEARTEXT_MAX_HCU_PER_TX = 20000000n;

export const FHEVM_MNEMONIC = 'test test test test test test test future home engine virtual motion';

export const CLEARTEXT_COPROCESSORS_MNEMONIC = FHEVM_MNEMONIC;

export const CLEARTEXT_COPROCESSORS_MNEMONIC_PATH = "m/44'/60'/0'/2/";

export const CLEARTEXT_COPROCESSORS_MNEMONIC_INDEX = 0;

export const CLEARTEXT_KMS_NODES_MNEMONIC = FHEVM_MNEMONIC;

export const CLEARTEXT_KMS_NODES_MNEMONIC_PATH = "m/44'/60'/0'/3/";

export const CLEARTEXT_KMS_NODES_MNEMONIC_INDEX = 0;

export const CLEARTEXT_KMS_NODES_TX_SENDER_MNEMONIC = FHEVM_MNEMONIC;

export const CLEARTEXT_KMS_NODES_TX_SENDER_MNEMONIC_PATH = "m/44'/60'/0'/4/";

export const CLEARTEXT_KMS_NODES_TX_SENDER_MNEMONIC_INDEX = 0;

export const CLEARTEXT_KMS_NODE_IP_ADDRESS_PREFIX = '127.0.0.';

export const CLEARTEXT_KMS_NODE_STORAGE_URL_PREFIX = 's3://kms-bucket-';

export const CLEARTEXT_KMS_NODE_MPC_IDENTITY_PREFIX = 'kms-core-';

export const CLEARTEXT_KMS_NODE_MPC_IDENTITY_INFIX = '-cleartext-core-';

export const CLEARTEXT_KMS_NODE_PUBLIC_STORAGE_PREFIX = 'cleartext-';

export const CLEARTEXT_KMS_SOFTWARE_VERSION = '0.0.0-cleartext';

export const CLEARTEXT_KMS_NODE_CA_CERT = '0x';
