// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTOGENERATED by `npm run generate:local-host-bytecode` via `cast interface`.
// DO NOT EDIT — your changes will be overwritten. See internal/generateLocalHostBytecode.ts.

interface ICleartextDB {
    error AddressEmptyCode(address target);
    error CleartextErrorAccountAlreadyWriter(address account);
    error CleartextErrorAccountNotWriter(address account);
    error CleartextErrorInvalidNullWriter();
    error CleartextErrorNotWriter(address account);
    error ERC1967InvalidImplementation(address implementation);
    error ERC1967NonPayable();
    error FailedCall();
    error InvalidInitialization();
    error NotHostOwner(address sender);
    error NotInitializing();
    error NotInitializingFromEmptyProxy();
    error UUPSUnauthorizedCallContext();
    error UUPSUnsupportedProxiableUUID(bytes32 slot);

    event AddWriter(address indexed account);
    event Initialized(uint64 version);
    event RemoveWriter(address indexed account);
    event Upgraded(address indexed implementation);

    function IS_CLEARTEXT() external view returns (bool);
    function UPGRADE_INTERFACE_VERSION() external view returns (string memory);
    function addWriter(address account) external;
    function get(bytes32 handle) external view returns (uint256);
    function getACLAddress() external view returns (address);
    function getVersion() external pure returns (string memory);
    function initializeFromEmptyProxy(address initialWriter) external;
    function isWriter(address account) external view returns (bool);
    function proxiableUUID() external view returns (bytes32);
    function removeWriter(address account) external;
    function set(bytes32 handle, uint256 value) external;
    function upgradeToAndCall(address newImplementation, bytes memory data) external payable;
}
