// Generates pkg/src/FhevmStdVersion.sol from pkg/package.json.
//
// The version has to be readable from Solidity: a test that fails against the wrong library version
// should say so in the trace, and nothing else in a Forge run can see package.json. Derived rather
// than hand-written because two copies of a version number drift the moment one is bumped, and the
// npm one is authoritative — `fhevm-npm version` owns it through versions.json.
//
// Written into pkg/src, deliberately NOT into pkg/src/_host: that directory is owned outright by
// generateForgePayload.ts, which wipes it on every run. Two generators sharing a directory means one
// silently deletes the other's output depending on the order they happen to run in.

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

////////////////////////////////////////////////////////////////////////////////

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGE_JSON_PATH = join(ROOT, 'pkg', 'package.json');
const VERSION_SOL_PATH = join(ROOT, 'pkg', 'src', 'FhevmStdVersion.sol');

////////////////////////////////////////////////////////////////////////////////

function _render(version: string): string {
  return `// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// GENERATED by internal/generateVersion.ts - do not edit by hand.
// The source of truth is pkg/package.json#version.
library FhevmStdVersion {
    string internal constant VERSION = "${version}";
}
`;
}

////////////////////////////////////////////////////////////////////////////////

/** The published package's version, the one number this file is allowed to state. */
export function readVersion(): string {
  const pkg: unknown = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8'));
  if (typeof pkg !== 'object' || pkg === null || !('version' in pkg) || typeof pkg.version !== 'string') {
    throw new Error(`${PACKAGE_JSON_PATH}: no string "version" field`);
  }
  return pkg.version;
}

////////////////////////////////////////////////////////////////////////////////

/** Writes the constant. The only thing here that touches disk. */
export function writeVersion(): string {
  const version = readVersion();
  mkdirSync(dirname(VERSION_SOL_PATH), { recursive: true });
  writeFileSync(VERSION_SOL_PATH, _render(version), 'utf8');
  return version;
}
