// AUTO-GENERATED by `fhevm-npm generate cleartext-config` from sdk/cleartext-config.json — DO NOT EDIT.
//
// The v14-ONLY face: every constant whose `generations` names v14, in declaration order. These are values
// only v14's contracts have a field for, so they cannot ride the shared `cleartext-config.ts` — that module
// is copied into every generation, and a constant nothing else can consume does not belong in it.
//
// `fhevm-npm sync vendored` copies this file into v14's pkg/ts/ alone, next to the shared face, and
// v14's `test/cleartext-config-mirror.test.ts` checks the copy against the JSON. Import-free and
// browser-safe like the shared face: the generator emits nothing but `export const` literals.

export const CLEARTEXT_KMS_NODE_MPC_IDENTITY_PREFIX = 'kms-core-';

export const CLEARTEXT_KMS_NODE_MPC_IDENTITY_INFIX = '-cleartext-core-';

export const CLEARTEXT_KMS_NODE_PUBLIC_STORAGE_PREFIX = 'cleartext-';

export const CLEARTEXT_KMS_SOFTWARE_VERSION = '0.0.0-cleartext';

export const CLEARTEXT_KMS_NODE_CA_CERT = '0x';
