// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

/**
 * @title  LibFhevmCleartextConfig
 * @notice AUTO-GENERATED by `fhevm-npm generate cleartext-config` from cleartext-config.json — DO NOT
 *         EDIT. That JSON is where these values are decided, and where the long-form note on each one
 *         lives; regenerate with `make generate` after editing it.
 */
library LibFhevmCleartextConfig {
    /// The gateway chain id, hashed from a name so it cannot collide with a real network.
    // uint48(uint256(keccak256("fhevm.cheat.chainId cleartext gateway")))
    uint256 internal constant CLEARTEXT_GATEWAY_CHAIN_ID = 100733346448153;

    /// The relayer URL, on a `.foo` TLD that cannot be registered.
    string internal constant CLEARTEXT_RELAYER_URL = "https://relayer.cleartext.foo";

    /// Where the gateway's input-verification contract is said to live. Never deployed.
    // address(uint160(uint256(keccak256("fhevm.cheat.address cleartext input verification"))))
    address internal constant CLEARTEXT_INPUT_VERIFICATION_ADDRESS = 0x6189F6c0c3E40B4a3c72ec86262295D78d845297;

    /// Where the gateway's decryption contract is said to live. Never deployed.
    // address(uint160(uint256(keccak256("fhevm.cheat.address cleartext decryption"))))
    address internal constant CLEARTEXT_DECRYPTION_ADDRESS = 0xEaaA2FC6BC259dF015Aa7Dc8e59e0B67df622721;

    /// How many coprocessor signers the stack registers on `InputVerifier`.
    uint256 internal constant CLEARTEXT_COPROCESSOR_COUNT = 4;

    /// Signatures required on an input proof. Equal to the count, not a majority.
    uint256 internal constant CLEARTEXT_COPROCESSOR_THRESHOLD = 4;

    /// How many KMS nodes the stack registers.
    uint256 internal constant CLEARTEXT_KMS_NODE_COUNT = 4;

    /// The per-block HCU cap, at uint48 max so a test can never hit it.
    // type(uint48).max
    uint256 internal constant CLEARTEXT_HCU_CAP_PER_BLOCK = 281474976710655;

    /// The per-transaction depth bound, at the protocol's real default.
    uint256 internal constant CLEARTEXT_MAX_HCU_DEPTH_PER_TX = 5000000;

    /// The per-transaction total, at the protocol's real default.
    uint256 internal constant CLEARTEXT_MAX_HCU_PER_TX = 20000000;

    /// The signer-pool mnemonic. Published on purpose, and NOT the deploy mnemonic.
    string internal constant FHEVM_MNEMONIC = "test test test test test test test future home engine virtual motion";

    /// The mnemonic the coprocessor keys derive from.
    string internal constant CLEARTEXT_COPROCESSORS_MNEMONIC = FHEVM_MNEMONIC;

    /// The HD branch the coprocessor signer pool derives from.
    string internal constant CLEARTEXT_COPROCESSORS_MNEMONIC_PATH = "m/44'/60'/0'/2/";

    /// First index of the coprocessor pool, which runs to `INDEX + COUNT - 1`.
    uint32 internal constant CLEARTEXT_COPROCESSORS_MNEMONIC_INDEX = 0;

    /// The mnemonic the KMS signing keys derive from.
    string internal constant CLEARTEXT_KMS_NODES_MNEMONIC = FHEVM_MNEMONIC;

    /// The HD branch the KMS signing keys derive from.
    string internal constant CLEARTEXT_KMS_NODES_MNEMONIC_PATH = "m/44'/60'/0'/3/";

    /// First index of the KMS signing pool.
    uint32 internal constant CLEARTEXT_KMS_NODES_MNEMONIC_INDEX = 0;

    /// The mnemonic the KMS tx-sender keys derive from.
    string internal constant CLEARTEXT_KMS_NODES_TX_SENDER_MNEMONIC = FHEVM_MNEMONIC;

    /// The HD branch the KMS tx-senders derive from, distinct from the signing keys.
    string internal constant CLEARTEXT_KMS_NODES_TX_SENDER_MNEMONIC_PATH = "m/44'/60'/0'/4/";

    /// First index of the KMS tx-sender pool.
    uint32 internal constant CLEARTEXT_KMS_NODES_TX_SENDER_MNEMONIC_INDEX = 0;

    /// IP address prefix: node i gets `<prefix><i + 1>`, one-based.
    string internal constant CLEARTEXT_KMS_NODE_IP_ADDRESS_PREFIX = "127.0.0.";

    /// Storage URL prefix: node i gets `<prefix><i + 1>`, one-based like the IP prefix.
    string internal constant CLEARTEXT_KMS_NODE_STORAGE_URL_PREFIX = "s3://kms-bucket-";
}
