// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTOGENERATED by `npm run generate:local-host-bytecode` via `cast interface`.
// DO NOT EDIT — your changes will be overwritten. See internal/generateLocalHostBytecode.ts.

library IKMSGeneration {
    type KeyType is uint8;

    struct KeyDigest {
        KeyType keyType;
        bytes digest;
    }
}

interface IProtocolConfig {
    struct ChainUpgradeWindow {
        uint64 chainId;
        uint64 startBlock;
        uint64 endBlock;
    }

    struct EpochCrsResult {
        uint256 crsId;
        uint256 maxBitLength;
        bytes crsDigest;
        bytes signature;
    }

    struct EpochKeyResult {
        uint256 prepKeygenId;
        uint256 keyId;
        IKMSGeneration.KeyDigest[] keyDigests;
        bytes signature;
    }

    struct KmsNode {
        address txSenderAddress;
        address signerAddress;
        string ipAddress;
        string storageUrl;
    }

    struct KmsNodeParams {
        address txSenderAddress;
        address signerAddress;
        string ipAddress;
        string storageUrl;
        int32 partyId;
        string mpcIdentity;
        bytes caCert;
        string storagePrefix;
    }

    struct KmsThresholds {
        uint256 publicDecryption;
        uint256 userDecryption;
        uint256 kmsGen;
        uint256 mpc;
    }

    struct PcrValues {
        bytes pcr0;
        bytes pcr1;
        bytes pcr2;
    }

    error AddressEmptyCode(address target);
    error DuplicateChainId(uint64 chainId);
    error ECDSAInvalidSignature();
    error ECDSAInvalidSignatureLength(uint256 length);
    error ECDSAInvalidSignatureS(bytes32 s);
    error ERC1967InvalidImplementation(address implementation);
    error ERC1967NonPayable();
    error EmptyChainUpgradeWindows();
    error EmptyEpochActivationAttestation(uint256 epochId);
    error EmptyKmsNodes();
    error EmptySoftwareVersion();
    error EpochActivationAlreadyConfirmed(address signer, uint256 epochId);
    error EpochActivationSignerDoesNotMatchTxSender(address signer, address txSender);
    error EpochActivationUnauthorized(address caller, uint256 epochId);
    error FailedCall();
    error InvalidBlockWindow(uint64 chainId, uint64 startBlock, uint64 endBlock);
    error InvalidHighThreshold(string thresholdName, uint256 threshold, uint256 nodeCount);
    error InvalidInitialization();
    error InvalidKmsContext(uint256 kmsContextId);
    error InvalidKmsEpoch(uint256 epochId);
    error InvalidNullThreshold(string thresholdName);
    error InvalidProposalId();
    error KmsContextCreationAlreadyConfirmed(address txSender, uint256 kmsContextId);
    error KmsContextCreationUnauthorized(address caller, uint256 kmsContextId);
    error KmsContextNotCreated(uint256 kmsContextId);
    error KmsContextNotPending(uint256 kmsContextId);
    error KmsLifecycleOperationInFlight(uint256 kmsContextId, uint256 epochId);
    error KmsNodeNullSigner();
    error KmsNodeNullTxSender();
    error KmsSignerAlreadyRegistered(address signer);
    error KmsSignerSetExceedsProofFormatLimit(uint256 signerCount, uint256 maxAllowed);
    error KmsTxSenderAlreadyRegistered(address txSender);
    error LatestActiveKmsContextCannotBeDestroyed(uint256 kmsContextId);
    error LatestActiveKmsEpochCannotBeDestroyed(uint256 epochId);
    error NonIncreasingEpochId(uint256 epochId, uint256 currentEpochId);
    error NonIncreasingKmsContextId(uint256 contextId, uint256 latestActiveKmsContextId);
    error NotHostOwner(address sender);
    error NotInitializing();
    error NotInitializingFromEmptyProxy();
    error ThresholdExceedsProofFormatLimit(string thresholdName, uint256 threshold, uint256 maxAllowed);
    error UUPSUnauthorizedCallContext();
    error UUPSUnsupportedProxiableUUID(bytes32 slot);
    error ZeroChainId();
    error ZeroGwStartBlock();

    event ActivateEpoch(
        uint256 indexed kmsContextId,
        uint256 indexed epochId,
        EpochKeyResult[] keys,
        EpochCrsResult[] crsList,
        string[] kmsNodeStorageUrls
    );
    event CoprocessorUpgradeProposed(
        uint256 indexed proposalId,
        string softwareVersion,
        ChainUpgradeWindow[] chainUpgradeWindows,
        uint64 gwStartBlock
    );
    event EpochActivationConfirmation(uint256 indexed epochId, address indexed signer, bytes32 dataHash);
    event Initialized(uint64 version);
    event KmsContextCreationConfirmation(
        uint256 indexed kmsContextId, address indexed txSender, bool isPreviousTxSender, bool isNewTxSender
    );
    event KmsContextDestroyed(uint256 indexed kmsContextId);
    event KmsEpochDestroyed(uint256 indexed epochId);
    event KmsGenThresholdUpdated(uint256 indexed kmsContextId, uint256 threshold);
    event MirrorKmsContextAndEpoch(
        uint256 indexed contextId,
        uint256 indexed epochId,
        KmsNodeParams[] kmsNodeParams,
        KmsThresholds thresholds,
        string softwareVersion,
        PcrValues[] pcrValues
    );
    event MirrorKmsEpoch(uint256 indexed contextId, uint256 indexed epochId);
    event MpcThresholdUpdated(uint256 indexed kmsContextId, uint256 threshold);
    event NewKmsContext(
        uint256 indexed contextId,
        uint256 indexed previousContextId,
        KmsNodeParams[] kmsNodeParams,
        KmsThresholds thresholds,
        string softwareVersion,
        PcrValues[] pcrValues
    );
    event NewKmsEpoch(
        uint256 indexed kmsContextId,
        uint256 indexed epochId,
        uint256 previousContextId,
        uint256 previousEpochId,
        uint256 materialBlockNumber
    );
    event PublicDecryptionThresholdUpdated(uint256 indexed kmsContextId, uint256 threshold);
    event Upgraded(address indexed implementation);
    event UserDecryptionThresholdUpdated(uint256 indexed kmsContextId, uint256 threshold);

    function UPGRADE_INTERFACE_VERSION() external view returns (string memory);
    function confirmEpochActivation(uint256 epochId, EpochKeyResult[] memory keys, EpochCrsResult[] memory crsList)
        external;
    function confirmKmsContextCreation(uint256 kmsContextId) external;
    function defineNewEpochForCurrentKmsContext() external;
    function defineNewKmsContextAndEpoch(
        KmsNodeParams[] memory kmsNodeParams,
        KmsThresholds memory thresholds,
        string memory softwareVersion,
        PcrValues[] memory pcrValues
    ) external;
    function destroyKmsContext(uint256 kmsContextId) external;
    function destroyKmsEpoch(uint256 epochId) external;
    function getContextCreationPreviousTxSenderThreshold(uint256 kmsContextId) external view returns (uint256);
    function getCurrentKmsContextAndEpoch() external view returns (uint256 contextId, uint256 epochId);
    function getCurrentKmsContextId() external view returns (uint256);
    function getCurrentKmsContextIdCounter() external view returns (uint256);
    function getKmsContextAnchor(uint256 contextId)
        external
        view
        returns (uint256 emissionBlockNumber, bytes32 contextInfoHash);
    function getKmsGenThreshold() external view returns (uint256);
    function getKmsGenThresholdForContext(uint256 kmsContextId) external view returns (uint256);
    function getKmsNodeForContext(uint256 kmsContextId, address txSender) external view returns (KmsNode memory);
    function getKmsNodesForContext(uint256 kmsContextId) external view returns (KmsNode[] memory);
    function getKmsSigners() external view returns (address[] memory);
    function getKmsSignersForContext(uint256 kmsContextId) external view returns (address[] memory);
    function getMpcThreshold() external view returns (uint256);
    function getMpcThresholdForContext(uint256 kmsContextId) external view returns (uint256);
    function getPublicDecryptionThreshold() external view returns (uint256);
    function getPublicDecryptionThresholdForContext(uint256 kmsContextId) external view returns (uint256);
    function getUserDecryptionThreshold() external view returns (uint256);
    function getUserDecryptionThresholdForContext(uint256 kmsContextId) external view returns (uint256);
    function getVersion() external pure returns (string memory);
    function initializeFromCanonical(
        uint256 canonicalContextId,
        uint256 canonicalEpochId,
        KmsNodeParams[] memory canonicalKmsNodeParams,
        KmsThresholds memory canonicalThresholds
    ) external;
    function initializeFromEmptyProxy(
        KmsNodeParams[] memory initialKmsNodeParams,
        KmsThresholds memory initialThresholds,
        string memory softwareVersion,
        PcrValues[] memory pcrValues
    ) external;
    function isKmsSigner(address signer) external view returns (bool);
    function isKmsSignerForContext(uint256 kmsContextId, address signer) external view returns (bool);
    function isKmsTxSenderForContext(uint256 kmsContextId, address txSender) external view returns (bool);
    function isLiveKmsContext(uint256 kmsContextId) external view returns (bool);
    function isValidEpochForContext(uint256 kmsContextId, uint256 epochId) external view returns (bool);
    function isValidKmsContext(uint256 kmsContextId) external view returns (bool);
    function mirrorKmsContextAndEpoch(
        uint256 contextId,
        uint256 epochId,
        KmsNodeParams[] memory kmsNodeParams,
        KmsThresholds memory thresholds,
        string memory softwareVersion,
        PcrValues[] memory pcrValues
    ) external;
    function mirrorKmsEpoch(uint256 contextId, uint256 epochId) external;
    function proposeCoprocessorUpgrade(
        uint256 proposalId,
        string memory softwareVersion,
        ChainUpgradeWindow[] memory chainUpgradeWindows,
        uint64 gwStartBlock
    ) external;
    function proxiableUUID() external view returns (bytes32);
    function reinitializeV2(
        KmsNodeParams[] memory kmsNodeParams,
        string memory softwareVersion,
        PcrValues[] memory pcrValues
    ) external;
    function updateKmsGenThresholdForContext(uint256 kmsContextId, uint256 threshold) external;
    function updateMpcThresholdForContext(uint256 kmsContextId, uint256 threshold) external;
    function updatePublicDecryptionThresholdForContext(uint256 kmsContextId, uint256 threshold) external;
    function updateUserDecryptionThresholdForContext(uint256 kmsContextId, uint256 threshold) external;
    function upgradeToAndCall(address newImplementation, bytes memory data) external payable;
}
