name: Manual Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    permissions:
      contents: read # Required to checkout repository code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier:check
      - name: Run lint
        run: npm run lint
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run tests using Hardhat Node
        run: npm run test:node
      - name: Run tests using Anvil
        run: npm run test:anvil
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        with:
          persona: pedantic
          version: 1.14.2
