name: sdk-cleartext-tests

on:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: sdk-cleartext-tests/test (bpr)
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      contents: 'read' # Required to checkout this repository code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: placeholder
        run: |
          echo "placeholder job"
